### ISSUE TITLE
Full Code for model

### ISSUE THREAD

**Issue by KevinGoodman** [BFeng14/RobustDancer#1]
https://github.com/BFeng14/RobustDancer/blob/9dedf7a9e538ed5fd55cd1b39872d16b61401faf/models_final/condition_transformer_rawaistpp_style_hist_unpaired_v2.py#L14

Thanks for sharing the code, but it seems that some file is missing in the repo. Could you please upload the whole models_final ?

**Comment by BFeng14** [comment]
sorry for that, the mising essential model files is uploaded now.
